In [5]:
import numpy as np
import time

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
# time
size = 1_000_000

# python list
py_list = list(range(size))
start = time.time()
sq_list = [x ** 2 for x in py_list]
end = time.time()
print(f'python list time is: {end - start} seconds')

# numpy array
np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2 # vectorisation
end = time.time()
print(f'numpy array time is: {end - start} seconds')

python list time is: 0.8280861377716064 seconds
numpy array time is: 0.017776012420654297 seconds


In [10]:
# memory
import sys

print(f'python list size = {sys.getsizeof(py_list) * len(py_list)} bytes')
print(f'numpy array size = {np_arr.nbytes} bytes')

python list size = 8000056000000 bytes
numpy array size = 8000000 bytes


In [15]:
# creating numpy arrays
# creating from python lists
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1, type(arr1), arr1.dtype, arr1.shape)
arr2 = np.array([1, 2, 3, 4, 5, "six"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d, type(arr2d), arr2d.dtype, arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'six'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [26]:
# using built-in methods
arr1 = np.zeros((2, 3), dtype = "int64") # prefill with 0s
print(arr1, arr1.shape)

arr2 = np.ones((2, 3), dtype = "int64") # prefill with 1s
print(arr2, arr2.shape)

arr3 = np.full((5, ), 100, dtype = "int64") # prefill with any number of choice
print(arr3, arr3.shape)

arr4 = np.eye(3, dtype = "int64") # creates an identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1, 11, 2) 
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4, dtype = "int64")
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[100 100 100 100 100] (5,)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1  34  67 100] (4,)


In [27]:
# properties
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
print(arr.astype(np.float64))

(7,)
7
int64
1
[1. 2. 3. 4. 5. 6. 7.]


In [30]:
# operations
# reshaping
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped_arr = arr.reshape((3, 2))
print(reshaped_arr, reshaped_arr.shape)

flattened_arr = arr.flatten()
print(flattened_arr, flattened_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [38]:
# indexing
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1[0])
print(arr1[len(arr1) - 1])
print(arr2[0][0])
print(arr2[1][2])

# fancy indexing
idx = [1, 3, 5]
print(arr1[idx]) # vectorisation

# boolean indexing
print(arr[arr > 2]) # we can write conditions
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

1
6
1
6
[2 4 6]
[3 4 5 6]
[2 4 6]
[1 3 5]


In [39]:
# slicing
arr1 = np.array([1, 2, 3, 4, 5, 6])

print(arr1[1:4])
print(arr1[1:])
print(arr1[:4])
print(arr1[::2])

[2 3 4]
[2 3 4 5 6]
[1 2 3 4]
[1 3 5]


In [44]:
# copy vs view
# python list creates a copy
nums = [1, 2, 3, 4, 5, 6]
sub_list = nums[1:3]
sub_list[1] = 100
print(sub_list)
print(nums)

# numpy array creates a view
arr = np.array(nums)
sub_arr = arr[1:3]
sub_arr[1] = 100 # changes the original  array
print(sub_arr)
print(arr)

sub_arr = arr[1:3].copy() # creates a copy instead of a view
sub_arr[1] = 200 # doesn't affect the original array
print(sub_arr)
print(arr)

[2, 100]
[1, 2, 3, 4, 5, 6]
[  2 100]
[  1   2 100   4   5   6]
[  2 200]
[  1   2 100   4   5   6]


In [48]:
# common datatypes
arr = np.array([1, 2, 3, 4, 5]) 
print(arr.dtype)
arr = np.array([1, 2, 3.0, 4, 5], dtype = "float32") # downcasting
print(arr.dtype)

# complex numbers
arr1 = np.array([3 + 5j])
arr2 = np.array([7 + 9j])
sum = arr1 + arr2
print(sum, sum.dtype)

# not advised to store string or object datatyppe in numpy arrays
arr = np.array(["prime", {1, 2, 3}, 3.14]) 
print(arr.dtype)

int64
float32
[10.+14.j] complex128
object
